### ISSUE TITLE
Invalid configuration settings in json file

### ISSUE THREAD

**Issue by dkeza** [labstack/armor#15]
I have tried to add another host, which should be served as static website by Armor.
But I always get this error:

{"time":"2016-11-09T16:38:32+01:00","level":"-","prefix":"armor","file":"main.go","line":"86","message":"error parsing configuration file, type=type-error, expected=[]armor.Plugin, got=object, offset=72"}

I have tried latest Armor version, and version 0.15, i think.

When I grab configuration settings from Sample configuration from https://armor.labstack.com/guide/configuration and try to use it, i also get same error.

**Comment by vishr** [comment]
From 0.2.x onwards, plugins is an array instead of object. So make you sent plugs as array, e.g.

```js
{
    "address": ":8080",
    "plugins": [{
        "name": "logger"
    }, {
        "name": "static",
        "browse": true,
        "root": "."
    }]
}
```

**Comment by dkeza** [comment]
OK, thanks, it's working now.
