### ISSUE TITLE
confused, when i should armor and not echo?

### ISSUE THREAD

**Issue by mrwnmonm** [labstack/armor#19]

**Comment by painhardcore** [comment]
I suppose armor like nginx.Just web server.
Echo is a framework for development.

**Comment by mrwnmonm** [comment]
mmm, i got it, thanks

**Comment by CodinCat** [comment]
I think this is worth to add to README or a FAQ section.

**Comment by danqing** [comment]
+1 - @vishr can you add some official comparison in README? Was here to ask the same question.
