### ISSUE TITLE
"Let's Encrypt" | TLS-SNI challenge disabled

### ISSUE THREAD

**Issue by alexandreStein** [labstack/armor#30]
[Let's Encrypt has permanently disable the TLS-SNI challenge](https://community.letsencrypt.org/t/tls-sni-challenges-disabled-for-most-new-issuance/50316).

For what I see, `TLS-SNI` is the only way `Armor` and `Echo` can get certificates.

I tried to update `Echo` to use `HTTP-01` but it needs to use the other HTTP handler (port `80`).
This become a heavy work and I don't have the time to find a nice way to do it.

**Comment by alexandreStein** [comment]
Sorry but any news on this?

Thanks in advance.

**Comment by vishr** [comment]
@alexandreStein I will have a look soon, thanks.

**Comment by vishr** [comment]
Looks like `http-01` is the only  way for now, possibly `dns-01` in future https://github.com/golang/go/issues/23198. I will update the Echo auto-tls recipe and later modify Armor.
