### ISSUE TITLE
Store / Postgres doc

### ISSUE THREAD

**Issue by BigJoe01** [labstack/armor#35]
Plugins data stored in postgresql database, but documentation missing.
Panic called when settings not initializated.

**Comment by vishr** [comment]
@BigJoe01 How are you using the config? What version are you using?

**Comment by BigJoe01** [comment]
@vishr current master repository.

**Comment by vishr** [comment]
Ok, are you trying to using database for plugins or just the config file?

**Comment by BigJoe01** [comment]
Plugin store in database is forced?
I using simple config file, without specify database connection.

**Comment by vishr** [comment]
> Plugin store in database is forced?
No

Let me check on it, but you should use a released version.

**Comment by BigJoe01** [comment]
Sorry, next time i sending detailed report , but this is the first time quick test.
Thx the help.

**Comment by vishr** [comment]
Can you provide your config to reproduce the issue?
