### ISSUE TITLE
Port 80/443 and tls error, {"time":"2016-09-30T15:49:30-03:00","level":"FATAL","prefix":"armor","file":"asm_amd64.s","line":"2086","message":"open : no such file or directory"}

### ISSUE THREAD

**Issue by bradparks** [labstack/armor#6]
Hey! This looks super cool, and I can get it to work fine with non privileged ports, but get fails when trying to use the LetsEncrypt support. I tried to use a slightly modded config from your README.md, but admittedly I may be trying stuff I shouldnt? 

I tried to run the following config using

```$ sudo armor -c /tmp/armor.json```

and get this fail:

```
{"time":"2016-09-30T15:53:26-03:00","level":"FATAL","prefix":"armor","file":"asm_amd64.s","line":"2086","message":"open : no such file or directory"}
```

Here's my config:
```
{
  "address": ":443",
  "tls": {
    "auto": true
  },
  "plugins": {
    "remove-trailing-slash": {
      "redirect_code": 301
    },
    "logger": {},
    "gzip": {}
  },
  "hosts": {
    "super.ez.com": {
      "plugins": {
          "cors": {},
          "proxy": {
              "targets": [{
                  "url": "http://api.ls"
              }]
          }
      }
    },
    "test.ez.com": {
      "plugins": {
        "non-www-redirect": {},
        "static": {
          "root": ".",
          "html5": true
        }
      }
    },
    "how.com": {
      "plugins": {
        "static": {
          "root": "."
        }
      }
    }
  }
}
```

Other than this, I think it'd be a good idea to:
- mention that `sudo` is required to run this on ports 80/443 
- not use a privileged port in your example in the README (ie use 8080)
- use "/var/www/html" as your example root html folder
- supply lots of example configs
- have at least one simple LetEncrypt example that describes the setup required, if any!

Thanks a ton again!

**Comment by chrisLeeTW** [comment]
I also have trouble with setup letEncrypt auto mode, which show the same error.

**Comment by vishr** [comment]
`address` is for http. For auto TLS you don't need to specify any address, as it always has to be 443. Let me know how that goes.

**Comment by linki** [comment]
@bradparks you need to specify a `cache_file` to get rid of your error.

try:
```
{
  "tls": {
    "auto": true,
    "cache_file": ".armor"
  },
  ...
```

also drop `"address": ":443"` as it specifies port 443 for your http listener which will then clash with the https listener (because it always listens on 443 as @vishr mentioned)

**Comment by painhardcore** [comment]
Need to update examples on site.
